# Generated by Django 4.2.30 on 2026-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('source', models.CharField(default='frontend', max_length=80, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('category', models.CharField(max_length=80, verbose_name='Category')),
                ('price', models.CharField(max_length=40, verbose_name='Display price')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='Tag')),
                ('tone', models.CharField(blank=True, max_length=40, verbose_name='Color tone')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('note', models.TextField(verbose_name='Short description')),
                ('material', models.CharField(blank=True, max_length=240, verbose_name='Material')),
                ('care', models.CharField(blank=True, max_length=240, verbose_name='Care')),
                ('fit', models.CharField(blank=True, max_length=240, verbose_name='Fit')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contact inquiry', 'verbose_name_plural': 'Contact inquiries'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='budget_range',
            field=models.CharField(max_length=80, verbose_name='Budget range'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_brand',
            field=models.CharField(max_length=120, verbose_name='Company / brand'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(max_length=80, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_city',
            field=models.CharField(max_length=80, verbose_name='Delivery city'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='estimated_quantity',
            field=models.CharField(max_length=80, verbose_name='Estimated quantity'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project_type',
            field=models.CharField(max_length=80, verbose_name='Project type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='requirement',
            field=models.TextField(verbose_name='Requirement'),
        ),
    ]
