# Generated by Django 4.2.30 on 2026-06-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '联系询盘', 'verbose_name_plural': '联系询盘'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ('-created_at',), 'verbose_name': '邮件订阅', 'verbose_name_plural': '邮件订阅'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='budget_range',
            field=models.CharField(max_length=80, verbose_name='预算区间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_brand',
            field=models.CharField(max_length=120, verbose_name='公司 / 品牌'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(max_length=80, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_city',
            field=models.CharField(max_length=80, verbose_name='交付城市'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='estimated_quantity',
            field=models.CharField(max_length=80, verbose_name='预计数量'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project_type',
            field=models.CharField(max_length=80, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='requirement',
            field=models.TextField(verbose_name='需求说明'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订阅时间'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(default='frontend', max_length=80, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care',
            field=models.CharField(blank=True, max_length=240, verbose_name='护理方式'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=80, verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, max_length=240, verbose_name='适用场景'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=240, verbose_name='材质说明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(verbose_name='简短描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=40, verbose_name='展示价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='商品标识'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=80, verbose_name='商品标签'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tone',
            field=models.CharField(blank=True, max_length=40, verbose_name='色彩风格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
