# Generated by Django 4.2.30 on 2026-06-27 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Order number')),
                ('customer_name', models.CharField(max_length=80, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=40, verbose_name='WhatsApp / Phone')),
                ('country', models.CharField(max_length=80, verbose_name='Country')),
                ('address', models.TextField(verbose_name='Address')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total price')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ('-created_at',), 'verbose_name': 'Newsletter subscriber', 'verbose_name_plural': 'Newsletter subscribers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='contract',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contract',
            name='interested_products',
            field=models.TextField(blank=True, default='', verbose_name='Interested products'),
        ),
        migrations.AddField(
            model_name='contract',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contract',
            name='source',
            field=models.CharField(default='website', max_length=80, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='budget_range',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Budget range'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_brand',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Company / brand'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Legacy contact name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_city',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Delivery city'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='estimated_quantity',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Estimated quantity'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='WhatsApp / Phone'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Project type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='requirement',
            field=models.TextField(blank=True, default='', verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Subscribed at'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(default='frontend', max_length=80, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care',
            field=models.CharField(blank=True, max_length=240, verbose_name='Care'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=80, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, max_length=240, verbose_name='Fit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=240, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=40, verbose_name='Display price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='Product slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=80, verbose_name='Product tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Color tone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(max_length=80, verbose_name='Product slug')),
                ('product_name', models.CharField(max_length=120, verbose_name='Product name')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('display_price', models.CharField(max_length=40, verbose_name='Display price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
    ]
