# Generated by Django 4.2.30 on 2026-06-27 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': '询盘', 'verbose_name_plural': '询盘'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ('-created_at',), 'verbose_name': '邮件订阅', 'verbose_name_plural': '邮件订阅'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='budget_range',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='预算范围'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_brand',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='公司 / 品牌'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='旧版联系人姓名'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_city',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='收货城市'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='estimated_quantity',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='预计数量'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='interested_products',
            field=models.TextField(blank=True, default='', verbose_name='感兴趣商品'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='WhatsApp / 电话'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='requirement',
            field=models.TextField(blank=True, default='', verbose_name='需求说明'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='source',
            field=models.CharField(default='website', max_length=80, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订阅时间'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(default='frontend', max_length=80, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=80, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=80, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='邮件已发送'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=24, unique=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='WhatsApp / 电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', '新订单'), ('contacted', '已联系'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='new', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='display_price',
            field=models.CharField(max_length=40, verbose_name='展示价格'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=120, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_slug',
            field=models.SlugField(max_length=80, verbose_name='商品别名'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care',
            field=models.CharField(blank=True, max_length=240, verbose_name='护理说明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=80, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, max_length=240, verbose_name='适用范围'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=240, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(verbose_name='简短描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=40, verbose_name='展示价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='商品别名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=80, verbose_name='商品标签'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tone',
            field=models.CharField(blank=True, max_length=40, verbose_name='色调'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
